GET http://localhost:3000/students
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50cyI6eyJpZCI6IjY1YTQ0Y2JmNTVjMjc0MDkxOTM3M2IwOSIsInJvbGUiOiJBZG1pbiJ9LCJpYXQiOjE3MDU0MDUzMjF9.hgRAW8WRKNaR2c8B391rgbCkMMi7BM-cNF2X_2OpzRM


###

GET http://localhost:3000/students/659bd3e6941203552bc86c2e

###

POST http://localhost:3000/students/
Content-Type: application/json

{

        "name": "Shashikant",
        "email": "Shashikant1235@gmail.com",
        "password": "abcd@12354",
        "address": "B15 Jai bhawani phase one bhopal",
        "phone": "9786354736",
        "parentsphone": "7100953835",
        "photo": "photorahul23.jpg",
        "documentid": "aadharahul13.jpg",
        "role": "Student",
        "uid": "240116AD04"
}

### Deleting students

DELETE http://localhost:3000/students/65a2f95614c7499e7cecb9e3
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50cyI6eyJpZCI6IjY1YTQ0Y2JmNTVjMjc0MDkxOTM3M2IwOSIsInJvbGUiOiJBZG1pbiJ9LCJpYXQiOjE3MDU0MDUzMjF9.hgRAW8WRKNaR2c8B391rgbCkMMi7BM-cNF2X_2OpzRM


###
PATCH http://localhost:3000/students/659c71e7fa6b28a0ace5c9e6
Content-Type: application/json

{
    "name": "Amar Ratna",
    "role": "Admin"
}

###

POST http://localhost:3000/students/login
Content-Type: application/json

{
    "email": "Shashikant123@gmail.com",
    "password": "abcd@12354"
}

### Get the user

POST http://localhost:3000/students/getuser
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50cyI6eyJpZCI6IjY1YTJmOTU2MTRjNzQ5OWU3Y2VjYjllMyIsInJvbGUiOiJTdHVkZW50In0sImlhdCI6MTcwNTMxMzM4NX0.SFD15fRHYYY3LR4Kh_hpOUvbU2WJZBtW2bR9lAzFotY

### fetch all seats
GET http://localhost:3000/seats/fetchallseats
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50cyI6eyJpZCI6IjY1OWM3MWU3ZmE2YjI4YTBhY2U1YzllNiJ9LCJpYXQiOjE3MDQ5Njc2Mzl9.qDt8fBturhekxtvq0gDJUpTwIfeN2Z41htdClwJQH-Y

### add a seat
POST  http://localhost:3000/seats/addaseat
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50cyI6eyJpZCI6IjY1YTQ0Y2JmNTVjMjc0MDkxOTM3M2IwOSIsInJvbGUiOiJBZG1pbiJ9LCJpYXQiOjE3MDUzMDk2NTN9.xKFqP1YPaEDGrAQjlR_qrjxm4oD1FMWfvZH9F9xbjxU

{
    "seatNumber": "S07",
    "seatLocation": "4FC",
    "seatStatus": true,
    "slot": "Afternoon"
}


### fetch all bookings
GET http://localhost:3000/bookings/getbooking
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50cyI6eyJpZCI6IjY1OWM3MWU3ZmE2YjI4YTBhY2U1YzllNiJ9LCJpYXQiOjE3MDQ5Njc2Mzl9.qDt8fBturhekxtvq0gDJUpTwIfeN2Z41htdClwJQH-Y

### Book a seat
POST  http://localhost:3000/bookings/bookaseat
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50cyI6eyJpZCI6IjY1OWM3MWU3ZmE2YjI4YTBhY2U1YzllNiJ9LCJpYXQiOjE3MDQ5Njc2Mzl9.qDt8fBturhekxtvq0gDJUpTwIfeN2Z41htdClwJQH-Y

{
    "seatId": "65a433ac64f8f1572eac28bb",
    "slot": "Morning",
    "endDate": "15 Feb 2024"
}

### Update seats: require admin login
PATCH http://localhost:3000/seats//updateseats/65a5be70367a5d3dbb66f603
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50cyI6eyJpZCI6IjY1OWM3MWU3ZmE2YjI4YTBhY2U1YzllNiJ9LCJpYXQiOjE3MDQ5Njc2Mzl9.qDt8fBturhekxtvq0gDJUpTwIfeN2Z41htdClwJQH-Y
{
    "seatStatus": "false",
    "slot": "Morning"
}

### Delete a seat: require admin login
DELETE http://localhost:3000/seats//deleteseats/65a4339964f8f1572eac28b9
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50cyI6eyJpZCI6IjY1YTQ0Y2JmNTVjMjc0MDkxOTM3M2IwOSIsInJvbGUiOiJBZG1pbiJ9LCJpYXQiOjE3MDU0MDUzMjF9.hgRAW8WRKNaR2c8B391rgbCkMMi7BM-cNF2X_2OpzRM
